/*
 * myFortune
 * A "Fortune" server written in pure c++
 * (c) 2019 by Felice Murolo, all rigths reserved
 * Licensed under LGPL V 3.0
 * Location: Salerno, Italia
 * email: linuxboy@giove.tk
 */


#ifndef QUOTES_H
#define QUOTES_H

#include <list>
#include <iterator>

struct quote {
    const char *value;
    const char *author;
};

list<quote> quotes = {
{ "”Be yourself; everyone else is already taken.”", "[Oscar Wilde]" },
{ "”Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.”", "[Albert Einstein]" },
{ "”So many books, so little time.”", "[Frank Zappa]" },
{ "”Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.”", "[Bernard M. Baruch]" },
{ "”A room without books is like a body without a soul.”", "[Marcus Tullius Cicero]" },
{ "”You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth.”", "[William W. Purkey]" },
{ "”You know you're in love when you can't fall asleep because reality is finally better than your dreams.”", "[Dr. Seuss]" },
{ "”You only live once, but if you do it right, once is enough.”", "[Mae West]" },
{ "”Be the change that you wish to see in the world.”", "[Mahatma Gandhi]" },
{ "”In three words I can sum up everything I've learned about life: it goes on.”", "[Robert Frost]" },
{ "”If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.”", "[J.K. Rowling]" },
{ "”No one can make you feel inferior without your consent.”", "[Eleanor Roosevelt]" },
{ "”Friendship ... is born at the moment when one man says to another \"What! You too? I thought that no one but myself . . .”", "[C.S. Lewis]" },
{ "”If you tell the truth, you don't have to remember anything.”", "[Mark Twain]" },
{ "”I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.”", "[Maya Angelou]" },
{ "”A friend is someone who knows all about you and still loves you.”", "[Elbert Hubbard]" },
{ "”Always forgive your enemies; nothing annoys them so much.”", "[Oscar Wilde]" },
{ "”To live is the rarest thing in the world. Most people exist, that is all.”", "[Oscar Wilde]" },
{ "”Live as if you were to die tomorrow. Learn as if you were to live forever.”", "[Mahatma Gandhi]" },
{ "”Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.”", "[Martin Luther King Jr.]" },
{ "”I am so clever that sometimes I don't understand a single word of what I am saying.”", "[Oscar Wilde]" },
{ "”Without music, life would be a mistake.”", "[Friedrich Nietzsche]" },
{ "”We accept the love we think we deserve.”", "[Stephen Chbosky]" },
{ "”To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.”", "[Ralph Waldo Emerson]" },
{ "”Insanity is doing the same thing, over and over again, but expecting different results.”", "[Narcotics Anonymous]" },
{ "”It is better to be hated for what you are than to be loved for what you are not.”", "[Andre Gide]" },
{ "”It is our choices, Harry, that show what we truly are, far more than our abilities.”", "[J.K. Rowling]" },
{ "”Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”", "[Marilyn Monroe]" },
{ "”The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”", "[Jane Austen]" },
{ "”It does not do to dwell on dreams and forget to live.”", "[J.K. Rowling]" },
{ "”There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”", "[Albert Einstein]" },
{ "”As he read, I fell in love the way you fall asleep: slowly, and then all at once.”", "[John Green]" },
{ "”Good friends, good books, and a sleepy conscience: this is the ideal life.”", "[Mark Twain]" },
{ "”It is better to remain silent at the risk of being thought a fool, than to talk and remove all doubt of it.”", "[Maurice Switzer]" },
{ "”The fool doth think he is wise, but the wise man knows himself to be a fool.”", "[William Shakespeare]" },
{ "”We are all in the gutter, but some of us are looking at the stars.”", "[Oscar Wilde]" },
{ "”Life is what happens to us while we are making other plans.”", "[Allen Saunders]" },
{ "”Whenever you find yourself on the side of the majority, it is time to reform (or pause and reflect).”", "[Mark Twain]" },
{ "”Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.”", "[Neil Gaiman]" },
{ "”Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present.”", "[Bill Keane]" },
{ "”I have not failed. I've just found 10,000 ways that won't work.”", "[Thomas A. Edison]" },
{ "”A woman is like a tea bag; you never know how strong it is until it's in hot water.”", "[Eleanor Roosevelt]" },
{ "”The man who does not read has no advantage over the man who cannot read.”", "[Mark Twain]" },
{ "”It is not a lack of love, but a lack of friendship that makes unhappy marriages.”", "[Friedrich Nietzsche]" },
{ "”If you don't stand for something you will fall for anything.”", "[Gordon A. Eadie]" },
{ "”I may not have gone where I intended to go, but I think I have ended up where I needed to be.”", "[douglas adams]" },
{ "”I solemnly swear that I am up to no good.”", "[J.K. Rowling]" },
{ "”Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.”", "[Groucho Marx]" },
{ "”I like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.”", "[Dr. Seuss]" },
{ "”Love all, trust a few, do wrong to none.”", "[William Shakespeare]" },
{ "”A day without sunshine is like, you know, night.”", "[Steve Martin]" },
{ "”Never put off till tomorrow what may be done day after tomorrow just as well.”", "[Mark Twain]" },
{ "”A reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.”", "[George R.R. Martin]" },
{ "”That which does not kill us makes us stronger.”", "[Friedrich Nietzsche]" },
{ "”Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.”", "[Lao Tzu]" },
{ "”For every minute you are angry you lose sixty seconds of happiness.”", "[Ralph Waldo Emerson]" },
{ "”It is never too late to be what you might have been.”", "[George Eliot]" },
{ "”It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.”", "[J.K. Rowling]" },
{ "”If you judge people, you have no time to love them.”", "[Mother Teresa]" },
{ "”I love deadlines. I love the whooshing noise they make as they go by.”", "[Douglas Adams]" },
{ "”There is never a time or place for true love. It happens accidentally, in a heartbeat, in a single flashing, throbbing moment.”", "[Sarah Dessen]" },
{ "”My thoughts are stars I cannot fathom into constellations.”", "[John Green]" },
{ "”If you can't explain it to a six year old, you don't understand it yourself.”", "[Albert Einstein]" },
{ "”Love is that condition in which the happiness of another person is essential to your own.”", "[Robert A. Heinlein]" },
{ "”I'm not upset that you lied to me, I'm upset that from now on I can't believe you.”", "[Friedrich Nietzsche]" },
{ "”Anyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.”", "[Garrison Keillor]" },
{ "”There is no greater agony than bearing an untold story inside you.”", "[Maya Angelou]" },
{ "”I have always imagined that Paradise will be a kind of library.”", "[Jorge Luis Borges]" },
{ "”Everything you can imagine is real.”", "[Pablo Picasso]" },
{ "”Women and cats will do as they please, and men and dogs should relax and get used to the idea.”", "[Robert A. Heinlein]" },
{ "”If you only read the books that everyone else is reading, you can only think what everyone else is thinking.”", "[Haruki Murakami]" },
{ "”We don't see things as they are, we see them as we are.”", "[AnaÃ¯s Nin]" },
{ "”Sometimes the questions are complicated and the answers are simple.”", "[Dr. Seuss]" },
{ "”We read to know we're not alone.”", "[William Nicholson]" },
{ "”You love me. Real or not real? I tell him, \"Real.”", "[Suzanne Collins]" },
{ "”Never trust anyone who has not brought a book with them.”", "[Lemony Snicket]" },
{ "”All you need is love. But a little chocolate now and then doesn't hurt.”", "[Charles M. Schulz]" },
{ "”You can never get a cup of tea large enough or a book long enough to suit me.”", "[C.S. Lewis]" },
{ "”Beauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.”", "[Jim Henson]" },
{ "”Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?”", "[J.K. Rowling]" },
{ "”Today you are You, that is truer than true. There is no one alive who is Youer than You.”", "[Dr. Seuss]" },
{ "”To the well-organized mind, death is but the next great adventure.”", "[J.K. Rowling]" },
{ "”I'm not afraid of death; I just don't want to be there when it happens.”", "[Woody Allen]" },
{ "”If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.”", "[Albert Einstein]" },
{ "”If one cannot enjoy reading a book over and over again, there is no use in reading it at all.”", "[Oscar Wilde]" },
{ "”Life isn't about finding yourself. Life is about creating yourself.”", "[George Bernard Shaw]" },
{ "”Whenever I feel the need to exercise, I lie down until it goes away.”", "[Paul   Terry]" },
{ "”Logic will get you from A to Z; imagination will get you everywhere.”", "[Albert Einstein]" },
{ "”You don't get to choose if you get hurt in this world...but you do have some say in who hurts you. I like my choices.”", "[John Green]" },
{ "”The more that you read, the more things you will know. The more that you learn, the more places you'll go.”", "[Dr. Seuss]" },
{ "”Sometimes people are beautiful.Not in looks.Not in what they say.Just in what they are.”", "[Markus Zusak]" },
{ "”Folks are usually about as happy as they make their minds up to be.”", "[Abraham Lincoln]" },
{ "”The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for.”", "[Bob Marley]" },
{ "”One good thing about music, when it hits you, you feel no pain.”", "[Bob Marley]" },
{ "”Love looks not with the eyes, but with the mind,And therefore is winged Cupid painted blind.”", "[William Shakespeare]" },
{ "”Do what you can, with what you have, where you are.”", "[Theodore Roosevelt]" },
{ "”Not all of us can do great things. But we can do small things with great love.”", "[Mother Teresa]" },
{ "”There is no friend as loyal as a book.”", "[Ernest Hemingway]" },
{ "”If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.”", "[Joan Powers]" },
{ "”I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.”", "[Groucho Marx]" },
{ "”Love is like the wind, you can't see it but you can feel it.”", "[Nicholas Sparks]" },
{ "”When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.”", "[Helen Keller]" },
{ "”The story so far:In the beginning the Universe was created.This has made a lot of people very angry and been widely regarded as a bad move.”", "[Douglas Adams]" },
{ "”It matters not what someone is born, but what they grow to be.”", "[J.K. Rowling]" },
{ "”Success is not final, failure is not fatal: it is the courage to continue that counts.”", "[Winston S. Churchill]" },
{ "”The difference between genius and stupidity is: genius has its limits.”", "[Alexandre Dumas-fils]" },
{ "”You don't love someone because they're perfect, you love them in spite of the fact that they're not.”", "[Jodi Picoult]" },
{ "”Life is like riding a bicycle. To keep your balance, you must keep moving.”", "[Albert Einstein]" },
{ "”If you can make a woman laugh, you can make her do anything.”", "[Marilyn Monroe]" },
{ "”So, this is my life. And I want you to know that I am both happy and sad and I'm still trying to figure out how that could be.”", "[Stephen Chbosky]" },
{ "”I would venture to guess that Anon, who wrote so many poems without signing them, was often a woman.”", "[Virginia Woolf]" },
{ "”Some infinities are bigger than other infinities.”", "[John Green]" },
{ "”Some people never go crazy. What truly horrible lives they must lead.”", "[Charles Bukowski]" },
{ "”There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.”", "[Jane Austen]" },
{ "”Do one thing every day that scares you.”", "[Eleanor Roosevelt]" },
{ "”The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.”", "[Terry Pratchett]" },
{ "”It is what you read when you don't have to that determines what you will be when you can't help it.”", "[Oscar Wilde]" },
{ "”Time you enjoy wasting is not wasted time.”", "[Marthe Troly-Curtin]" },
{ "”If I had a flower for every time I thought of you...I could walk through my garden forever.”", "[Alfred Tennyson]" },
{ "”Reality continues to ruin my life.”", "[Bill Watterson]" },
{ "”The real lover is the man who can thrill you by kissing your forehead or smiling into your eyes or just staring into space.”", "[Marilyn Monroe]" },
{ "”Who are you to judge the life I live?I know I'm not perfect-and I don't live to be-but before you start pointing fingers...make sure you hands are clean!”", "[Bob Marley]" },
{ "”Things change. And friends leave. Life doesn't stop for anybody.”", "[Stephen Chbosky]" },
{ "”Not all those who wander are lost.”", "[J.R.R. Tolkien]" },
{ "”He's like a drug for you, Bella.”", "[Stephenie Meyer]" },
{ "”Piglet sidled up to Pooh from behind. \"Pooh!\" he whispered.\"Yes, Piglet?\" \"Nothing,\" said Piglet, taking Pooh's paw. \"I just wanted to be sure of you.”", "[A.A. Milne]" },
{ "”A wise girl kisses but doesn't love, listens but doesn't believe, and leaves before she is left.”", "[Marilyn Monroe]" },
{ "”\"One must always be careful of books, said Tessa,\" \"and what is inside them, for words have the power to change us.”", "[Cassandra Clare]" },
{ "”The only way out of the labyrinth of suffering is to forgive.”", "[John Green]" },
{ "”Do not pity the dead, Harry. Pity the living, and, above all those who live without love.”", "[J.K. Rowling]" },
{ "”I am good, but not an angel. I do sin, but I am not the devil. I am just a small girl in a big world trying to find someone to love.”", "[Marilyn Monroe]" },
{ "”Go to heaven for the climate and hell for the company.”", "[Benjamin Franklin Wade]" },
{ "”If there's a book that you want to read, but it hasn't been written yet, then you must write it.”", "[Toni Morrison]" },
{ "”When someone loves you, the way they talk about you is different. You feel safe and comfortable.”", "[Jess C. Scott]" },
{ "”There is nothing to writing. All you do is sit down at a typewriter and bleed.”", "[Ernest Hemingway]" },
{ "”You may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.”", "[John Lennon]" },
{ "”I love mankind ... it's people I can't stand!!”", "[Charles M. Schulz]" },
{ "”I am free of all prejudice. I hate everyone equally. ”", "[W.C. Fields]" },
{ "”And, when you want something, all the universe conspires in helping you to achieve it.”", "[Paulo Coelho]" },
{ "”The marks humans leave are too often scars.”", "[John Green]" },
{ "”Remember, we're madly in love, so it's all right to kiss me anytime you feel like it.”", "[Suzanne Collins]" },
{ "”I have never let my schooling interfere with my education.”", "[Mark Twain]" },
{ "”What a slut time is. She screws everybody.”", "[John Green]" },
{ "”You never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.”", "[Harper Lee]" },
{ "”To die will be an awfully big adventure.”", "[J.M. Barrie]" },
{ "”It takes courage to grow up and become who you really are.”", "[E.E. Cummings]" },
{ "”Anyone who has never made a mistake has never tried anything new.”", "[Albert Einstein]" },
{ "”There is nothing better than a friend, unless it is a friend with chocolate.”", "[Linda Grayson]" },
{ "”A lady's imagination is very rapid; it jumps from admiration to love, from love to matrimony in a moment.”", "[Jane Austen]" },
{ "”We believe in ordinary acts of bravery, in the courage that drives one person to stand up for another.”", "[Veronica Roth]" },
{ "”You have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children.”", "[Madeleine L'Engle]" },
{ "”I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”", "[Jimi Hendrix]" },
{ "”Some day you will be old enough to start reading fairy tales again.”", "[C.S. Lewis]" },
{ "”And in that moment, I swear we were infinite.”", "[Stephen Chbosky]" },
{ "”But better to get hurt by the truth than comforted with a lie.”", "[Khaled Hosseini]" },
{ "”The books that the world calls immoral are books that show the world its own shame.”", "[Oscar Wilde]" },
{ "”We are what we pretend to be, so we must be careful about what we pretend to be.”", "[Kurt Vonnegut]" },
{ "”... a mind needs books as a sword needs a whetstone, if it is to keep its edge.”", "[George R.R. Martin]" },
{ "”\"The truth.\" Dumbledore sighed. \"It is a beautiful and terrible thing, and should therefore be treated with great caution.”", "[J.K. Rowling]" },
{ "”Books are a uniquely portable magic.”", "[Stephen King]" },
{ "”The truth is rarely pure and never simple.”", "[Oscar Wilde]" },
{ "”I believe in Christianity as I believe that the sun has risen: not only because I see it, but because by it I see everything else.”", "[C.S. Lewis]" },
{ "”Be nice to nerds. You may end up working for them. We all could.”", "[Charles J. Sykes]" },
{ "”The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.”", "[Mark Twain]" },
{ "”A lie can travel half way around the world while the truth is putting on its shoes.”", "[Mark Twain]" },
{ "”Just when you think it can't get any worse, it can. And just when you think it can't get any better, it can.”", "[Nicholas Sparks]" },
{ "”Never tell the truth to people who are not worthy of it.”", "[Mark Twain]" },
{ "”Tis better to have loved and lostThan never to have loved at all.”", "[Alfred Lord Tennyson]" },
{ "”Memories warm you up from the inside. But they also tear you apart.”", "[Haruki Murakami]" },
{ "”It's so hard to forget pain, but it's even harder to remember sweetness. We have no scar to show for happiness. We learn so little from peace.”", "[Chuck Palahniuk]" },
{ "”Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.”", "[William Shakespeare]" },
{ "”What you're supposed to do when you don't like a thing is change it. If you can't change it, change the way you think about it. Don't complain.”", "[Maya Angelou]" },
{ "”Knowing yourself is the beginning of all wisdom.”", "[Aristotle]" },
{ "”I love you as certain dark things are to be loved, in secret, between the shadow and the soul.”", "[Pablo Neruda]" },
{ "”A day without laughter is a day wasted.”", "[Nicolas Chamfort]" },
{ "”A person's a person, no matter how small.”", "[Dr. Seuss]" },
{ "”It's the possibility of having a dream come true that makes life interesting.”", "[Paulo Coelho]" },
{ "”Happiness in intelligent people is the rarest thing I know.”", "[Ernest Hemingway]" },
{ "”Only the very weak-minded refuse to be influenced by literature and poetry.”", "[Cassandra Clare]" },
{ "”Thomas Edison's last words were \"It's very beautiful over there. I don't know where there is, but I believe it's somewhere, and I hope it's beautiful.”", "[John Green]" },
{ "”\"Jesus!\" Luke exclaimed. \"Actually, it's just me,\" said Simon. \"Although I've been told the resemblance is startling.”", "[Cassandra Clare]" },
{ "”Oh, I wouldn't mind, Hazel Grace. It would be a privilege to have my heart broken by you.”", "[John Green]" },
{ "”Just because you have the emotional range of a teaspoon doesn't mean we all have.”", "[J.K. Rowling]" },
{ "”Numbing the pain for a while will make it worse when you finally feel it.”", "[J.K. Rowling]" },
{ "”Be careful about reading health books. Some fine day you'll die of a misprint.”", "[Markus Herz]" },
{ "”I became insane, with long intervals of horrible sanity.”", "[Edgar Allan Poe]" },
{ "”It is one of the blessings of old friends that you can afford to be stupid with them.”", "[Ralph Waldo Emerson]" },
{ "”The only true wisdom is in knowing you know nothing.”", "[Socrates]" },
{ "”The one you love and the one who loves you are never, ever the same person.”", "[Chuck Palahniuk]" },
{ "”An eye for an eye will only make the whole world blind.”", "[Mahatma Gandhi]" },
{ "”You can't live your life for other people. You've got to do what's right for you, even if it hurts some people you love.”", "[Nicholas Sparks]" },
{ "”You can never be overdressed or overeducated.”", "[Oscar Wilde]" },
{ "”If you're gonna be two-faced at least make one of them pretty.”", "[Marilyn Monroe]" },
{ "”Those who don't believe in magic will never find it.”", "[Roald Dahl]" },
{ "”Books are the quietest and most constant of friends; they are the most accessible and wisest of counselors, and the most patient of teachers.”", "[Charles W. Eliot]" },
{ "”So I walked back to my room and collapsed on the bottom bunk, thinking that if people were rain, I was drizzle and she was a hurricane.”", "[John Green]" },
{ "”Perhaps one did not want to be loved so much as to be understood.”", "[George Orwell]" },
{ "”I would rather walk with a friend in the dark, than alone in the light.”", "[Helen Keller]" },
{ "”Is this the part where you start tearing off strips of your shirt to bind my wounds?""If you wanted me to rip my clothes off, you should have just asked.”", "[Cassandra Clare]" },
{ "”I speak to everyone in the same way, whether he is the garbage man or the president of the university.”", "[Albert Einstein]" },
{ "”The truth will set you free, but first it will piss you off.”", "[Joe Klaas]" },
{ "”Until I feared I would lose it, I never loved to read. One does not love breathing.”", "[Harper Lee]" },
{ "”Creativity is knowing how to hide your sources”", "[C.E.M. Joad]" },
{ "”A great book should leave you with many experiences, and slightly exhausted at the end. You live several lives while reading.”", "[William Styron]" },
{ "”Fate is like a strange, unpopular restaurant filled with odd little waiters who bring you things you never asked for and don't always like.”", "[Lemony Snicket]" },
{ "”Music expresses that which cannot be put into words and that which cannot remain silent”", "[Victor hugo]" },
{ "”Life is an awful, ugly place to not have a best friend.”", "[Sarah Dessen]" },
{ "”I wish I could freeze this moment, right here, right now and live in it forever.”", "[Suzanne Collins]" },
{ "”A children's story that can only be enjoyed by children is not a good children's story in the slightest.”", "[C.S. Lewis]" },
{ "”If you don't have time to read, you don't have the time (or the tools) to write. Simple as that.”", "[Stephen King]" },
{ "”Happiness is when what you think, what you say, and what you do are in harmony.”", "[Mahatma Gandhi]" },
{ "”Keep away from people who try to belittle your ambitions. Small people always do that, but the really great make you feel that you, too, can become great.”", "[Mark Twain]" },
{ "”How wonderful it is that nobody need wait a single moment before starting to improve the world.”", "[Anne Frank]" },
{ "”We're all human, aren't we? Every human life is worth the same, and worth saving.”", "[J.K. Rowling]" },
{ "”The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.”", "[Isaac Asimov]" },
{ "”Well-behaved women seldom make history.”", "[Laurel Thatcher Ulrich]" },
{ "”Being a woman is a terribly difficult trade since it consists principally of dealings with men.”", "[Joseph Conrad]" },
{ "”You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.”", "[Albert Camus]" },
{ "”I am no bird; and no net ensnares me: I am a free human being with an independent will.”", "[Charlotte BrontÃ«]" },
{ "”It's the friends you can call up at 4 a.m. that matter.”", "[Marlene Dietrich]" },
{ "”The world is not a wish-granting factory.”", "[John Green]" },
{ "”Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life.”", "[Terry Pratchett]" },
{ "”Sometimes you have to be apart from people you love, but that doesn't make you love them any less. Sometimes you love them more.”", "[Nicholas Sparks]" },
{ "”When we love, we always strive to become better than we are. When we strive to become better than we are, everything around us becomes better too.”", "[Paulo Coelho]" },
{ "”Becoming fearless isn't the point. That's impossible. It's learning how to control your fear, and how to be free from it.”", "[Veronica Roth]" },
{ "”One is loved because one is loved. No reason is needed for loving.”", "[Paulo Coelho]" },
{ "”If you don't know where you're going, any road'll take you there”", "[George Harrison]" },
{ "”There's nothing like deep breaths after laughing that hard. Nothing in the world like a sore stomach for the right reasons.”", "[Stephen Chbosky]" },
{ "”I am not pretty. I am not beautiful. I am as radiant as the sun.”", "[Suzanne Collins]" },
{ "”With great power... comes great need to take a nap. Wake me up later.”", "[Rick Riordan]" },
{ "”If we find ourselves with a desire that nothing in this world can satisfy, the most probable explanation is that we were made for another world.”", "[C.S. Lewis]" },
{ "”You can love someone so much...But you can never love people as much as you can miss them.”", "[John Green]" },
{ "”Everyone thinks of changing the world, but no one thinks of changing himself.”", "[Leo Tolstoy]" },
{ "”I don't know half of you half as well as I should like; and I like less than half of you half as well as you deserve.”", "[J.R.R. Tolkien]" },
{ "”Love is needing someone. Love is putting up with someone's bad qualities because they somehow complete you.”", "[Sarah Dessen]" },
{ "”Nothing is impossible, the word itself says 'I'm possible'!”", "[Audrey Hepburn]" },
{ "”All God does is watch us and kill us when we get boring. We must never, ever be boring.”", "[Chuck Palahniuk]" },
{ "”What is the point of being alive if you don't at least try to do something remarkable?”", "[John Green]" },
{ "”So we beat on, boats against the current, borne back ceaselessly into the past.”", "[F. Scott Fitzgerald]" },
{ "”What a treacherous thing to believe that a person is more than a person.”", "[John Green]" },
{ "”Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.”", "[Virginia Woolf]" },
{ "”Every man has his secret sorrows which the world knows not; and often times we call a man cold when he is only sad.”", "[Henry Wadsworth Longfellow]" },
{ "”If you were half as funny as you think you are, you'd be twice as funny as you really are.”", "[H.N. Turteltaub]" },
{ "”You don't have to burn books to destroy a culture. Just get people to stop reading them.”", "[Ray Bradbury]" },
{ "”We love the things we love for what they are.”", "[Robert Frost]" },
{ "”I can't give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.”", "[Herbert Bayard Swope]" },
{ "”Maybe our favorite quotations say more about us than about the stories and people we're quoting.”", "[John Green]" },
{ "”I refuse to answer that question on the grounds that I don't know the answer”", "[Douglas Adams]" },
{ "”It takes ten times as long to put yourself back together as it does to fall apart.”", "[Suzanne Collins]" },
{ "”Sometimes I can hear my bones straining under the weight of all the lives I'm not living.”", "[Jonathan Safran Foer]" },
{ "”There is only one thing that makes a dream impossible to achieve: the fear of failure.”", "[Paulo Coelho]" },
{ "”In vain have I struggled. It will not do. My feelings will not be repressed. You must allow me to tell you how ardently I admire and love you.”", "[Jane Austen]" },
{ "”I would die for you. But I won't live for you.”", "[Stephen Chbosky]" },
{ "”We are only as strong as we are united, as weak as we are divided.”", "[J.K. Rowling]" },
{ "”Happiness is not something ready made. It comes from your own actions.”", "[Dalai Lama XIV]" },
{ "”Sometimes you wake up. Sometimes the fall kills you. And sometimes, when you fall, you fly.”", "[Neil Gaiman]" },
{ "”The weak can never forgive. Forgiveness is the attribute of the strong.”", "[Mahatma Gandhi]" },
{ "”Count your age by friends, not years. Count your life by smiles, not tears.”", "[John Lennon]" },
{ "”Peace begins with a smile..”", "[Mother Teresa]" },
{ "”Death ends a life, not a relationship.”", "[Mitch Albom]" },
{ "”\"We came to see Jace. Is he alright?\" \"I don't know,\" Magnus said. \"Does he normally just lie on the floor like that without moving?”", "[Cassandra Clare]" },
{ "”Indifference and neglect often do much more damage than outright dislike.”", "[J.K. Rowling]" },
{ "”So, I love you because the entire universe conspired to help me find you.”", "[Paulo Coelho]" },
{ "”He can run faster than Severus Snape confronted with shampoo.”", "[J.K. Rowling]" },
{ "”Never doubt that a small group of thoughtful, committed, citizens can change the world. Indeed, it is the only thing that ever has.”", "[Margaret Mead]" },
{ "”Do not read, as children do, to amuse yourself, or like the ambitious, for the purpose of instruction. No, read in order to live.”", "[Gustave Flaubert]" },
{ "”All that we see or seem is but a dream within a dream.”", "[Edgar Allan Poe]" },
{ "”The Christian does not think God will love us because we are good, but that God will make us good because He loves us.”", "[C.S. Lewis]" },
{ "”You are, and always have been, my dream.”", "[Nicholas Sparks]" },
{ "”The only thing worse than a boy who hates you: a boy that loves you.”", "[Markus Zusak]" },
{ "”Hold fast to dreams,For if dreams dieLife is a broken-winged bird,That cannot fly.”", "[Langston Hughes]" },
{ "”Most people are other people. Their thoughts are someone else's opinions, their lives a mimicry, their passions a quotation.”", "[Oscar Wilde]" },
{ "”Never memorize something that you can look up.”", "[Albert Einstein]" },
{ "”Never love anyone who treats you like you're ordinary.”", "[Oscar Wilde]" },
{ "”Don't think or judge, just listen.”", "[Sarah Dessen]" },
{ "”What lies behind us and what lies before us are tiny matters compared to what lies within us.”", "[Ralph Waldo Emerson]" },
{ "”I like the night. Without the dark, we'd never see the stars.”", "[Stephenie Meyer]" },
{ "”You cannot find peace by avoiding life.”", "[Michael Cunningham]" },
{ "”All we have to decide is what to do with the time that is given us.”", "[J.R.R. Tolkien]" },
{ "”Grief does not change you, Hazel. It reveals you.”", "[John Green]" },
{ "”Happy Hunger Games! And may the odds be ever in your favor.”", "[Suzanne Collins]" },
{ "”Those who believe in telekinetics, raise my hand.”", "[Kurt Vonnegut]" },
{ "”Promise me you'll always remember: You're braver than you believe, and stronger than you seem, and smarter than you think.”", "[Carter Crocker]" },
{ "”You talk when you cease to be at peace with your thoughts.”", "[Kahlil Gibran]" },
{ "”When you're in jail, a good friend will be trying to bail you out. A best friend will be in the cell next to you saying, 'Damn, that was fun'.”", "[Groucho Marx]" },
{ "”Friendship is unnecessary, like philosophy, like art.... It has no survival value; rather it is one of those things which give value to survival.”", "[C.S. Lewis]" },
{ "”I would always rather be happy than dignified.”", "[Charlotte BrontÃ«]" },
{ "”Whatever you are, be a good one.”", "[Abraham Lincoln]" },
{ "”In the depth of winter, I finally learned that within me there lay an invincible summer.”", "[Albert Camus]" },
{ "”There's a fine line between genius and insanity. I have erased this line.”", "[Oscar Levant]" },
{ "”When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity.”", "[Albert Einstein]" },
{ "”Facts do not cease to exist because they are ignored.”", "[Aldous Huxley]" },
{ "”When it comes down to it, I let them think what they want. If they care enough to bother with what I do, then I'm already better than them.”", "[Marilyn Monroe]" },
{ "”I hope she'll be a fool -- that's the best thing a girl can be in this world, a beautiful little fool.”", "[F. Scott Fitzgerald]" },
{ "”Where there is love there is life.”", "[Mahatma Gandhi]" },
{ "”Wicked people never have time for reading. It's one of the reasons for their wickedness.”", "[Lemony Snicket]" },
{ "”Two wrongs don't make a right, but they make a good excuse.”", "[Thomas Szasz]" },
{ "”Sleep is good, he said, and books are better.”", "[George R. R. Martin]" },
{ "”A good friend will always stab you in the front.”", "[Oscar Wilde]" },
{ "”Women are meant to be loved, not to be understood.”", "[Oscar Wilde]" },
{ "”First they ignore you. Then they ridicule you. And then they attack you and want to burn you. And then they build monuments to you.”", "[Nicholas Klein]" },
{ "”Be kind, for everyone you meet is fighting a harder battle.”", "[Plato]" },
{ "”If more of us valued food and cheer and song above hoarded gold, it would be a merrier world.”", "[J.R.R. Tolkien]" },
{ "”It means 'Shadowhunters: Looking Better in Black Than the Widows of our Enemies Since 1234'.”", "[Cassandra Clare]" },
{ "”Well, don't expect us to be too impressed. We just saw Finnick Odair in his underwear.”", "[Suzanne Collins]" },
{ "”Substitute 'damn' every time you're inclined to write 'very;' your editor will delete it and the writing will be just as it should be.”", "[Mark Twain]" },
{ "”May you live every day of your life.”", "[Jonathan Swift]" },
{ "”We all die. The goal isn't to live forever, the goal is to create something that will.”", "[Chuck Palahniuk]" },
{ "”Nobody has ever measured, not even poets, how much the heart can hold.”", "[Zelda Fitzgerald]" },
{ "”I love sleep. My life has the tendency to fall apart when I'm awake, you know?”", "[Ernest Hemingway]" },
{ "”Once upon a time there was a boy who loved a girl, and her laughter was a question he wanted to spend his whole life answering.”", "[Nicole Krauss]" },
{ "”I don't want to go to heaven. None of my friends are there.”", "[Oscar Wilde]" },
{ "”A clever person solves a problem. A wise person avoids it.”", "[Albert Einstein]" },
{ "”Chance is perhaps the pseudonym of God when he does not want to sign.”", "[ThÃ©ophile Gautier]" },
{ "”Destroying things is much easier than making them.”", "[Suzanne Collins]" },
{ "”When I look at my room, I see a girl who loves books.”", "[John Green]" },
{ "”You're a prefect? Oh Ronnie! That's everyone in the family!""What are Fred and I? Next door neighbors?”", "[J.K. Rowling]" },
{ "”It's only after we've lost everything that we're free to do anything.”", "[Chuck Palahniuk]" },
{ "”I have hated words and I have loved them, and I hope I have made them right.”", "[Markus Zusak]" },
{ "”We write to taste life twice, in the moment and in retrospect.”", "[Anais Nin]" },
{ "”Get busy living or get busy dying.”", "[Stephen King]" },
{ "”You educate a man; you educate a man. You educate a woman; you educate a generation.”", "[Brigham Young]" },
{ "”And those who were seen dancing were thought to be insane by those who could not hear the music.”", "[Friedrich Nietzsche]" },
{ "”These woods are lovely, dark and deep,But I have promises to keep,And miles to go before I sleep,And miles to go before I sleep.”", "[Robert Frost]" },
{ "”Science without religion is lame, religion without science is blind.”", "[Albert Einstein]" },
{ "”When someone shows you who they are believe them; the first time.”", "[Maya Angelou]" },
{ "”He's more myself than I am. Whatever our souls are made of, his and mine are the same.”", "[Emily BrontÃ«]" },
{ "”The meeting of two personalities is like the contact of two chemical substances: if there is any reaction, both are transformed.”", "[Carl Gustav Jung]" },
{ "”Man is the only creature who refuses to be what he is.”", "[Albert Camus]" },
{ "”Reader, suppose you were an idiot. And suppose you were a member of Congress. But I repeat myself.”", "[Mark Twain]" },
{ "”All the world is made of faith, and trust, and pixie dust.”", "[J.M. Barrie]" },
{ "”Doubt thou the stars are fire;Doubt that the sun doth move;Doubt truth to be a liar;But never doubt I love.”", "[William Shakespeare]" },
{ "”We should all start to live before we get too old. Fear is stupid. So are regrets.”", "[Marilyn Monroe]" },
{ "”We loved with a love that was more than love.”", "[Edgar Allen Poe]" },
{ "”You will always be fond of me. I represent to you all the sins you never had the courage to commit.”", "[Oscar Wilde]" },
{ "”You can't stay in your corner of the Forest waiting for others to come to you. You have to go to them sometimes.”", "[A.A. Milne]" },
{ "”It is sometimes an appropriate response to reality to go insane.”", "[Philip K. Dick]" },
{ "”Unless someone like you cares a whole awful lot,Nothing is going to get better. It's not.”", "[Dr. Seuss]" },
{ "”This is a good sign, having a broken heart. It means we have tried for something.”", "[Elizabeth Gilbert]" },
{ "”The fault, dear Brutus, is not in our stars, but in ourselves.”", "[William Shakespeare]" },
{ "”Some people care too much. I think it's called love.”", "[A.A. Milne]" },
{ "”Who controls the past controls the future. Who controls the present controls the past.”", "[George Orwell]" },
{ "”We have to dare to be ourselves, however frightening or strange that self may prove to be.”", "[May Sarton]" },
{ "”I do not want people to be very agreeable, as it saves me the trouble of liking them a great deal.”", "[Jane Austen]" },
{ "”How lucky I am to have known somebody and something that saying goodbye to is so damned awful.”", "[Evans G. Valens]" },
{ "”Anyone who lives within their means suffers from a lack of imagination.”", "[Oscar Wilde]" },
{ "”Some books should be tasted, some devoured, but only a few should be chewed and digested thoroughly.”", "[Sir Francis Bacon]" },
{ "”Eleanor was right. She never looked nice. She looked like art, and art wasn't supposed to look nice; it was supposed to make you feel something.”", "[Rainbow Rowell]" },
{ "”\"I might be in love with you.\" He smiles a little. \"I'm waiting until I'm sure to tell you, though.”", "[Veronica Roth]" },
{ "”It is the unknown we fear when we look upon death and darkness, nothing more.”", "[J.K. Rowling]" },
{ "”Isn't it nice to think that tomorrow is a new day with no mistakes in it yet?”", "[L.M. Montgomery]" },
{ "”Let us read, and let us dance; these two amusements will never do any harm to the world.”", "[Voltaire]" },
{ "”Never laugh at live dragons.”", "[J.R.R. Tolkien]" },
{ "”The planet is fine. The people are fucked.”", "[George Carlin]" },
{ "”If my life is going to mean anything, I have to live it myself.”", "[Rick Riordan]" },
{ "”Reading is one form of escape. Running for your life is another.”", "[Lemony Snicket]" },
{ "”Eating and reading are two pleasures that combine admirably.”", "[C.S. Lewis]" },
{ "”Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it.”", "[Rumi]" },
{ "”When I have a little money, I buy books; and if I have any left, I buy food and clothes.”", "[Desiderius Erasmus Roterodamus]" },
{ "”There are no good girls gone wrong - just bad girls found out.”", "[Mae West]" },
{ "”Never go to bed mad. Stay up and fight.”", "[Phyllis Diller]" },
{ "”Reality is merely an illusion, albeit a very persistent one.”", "[Albert Einstein]" },
{ "”I hope that in this year to come, you make mistakes. Because if you are making mistakes...you're Doing Something.”", "[Neil Gaiman]" },
{ "”Every saint has a past, and every sinner has a future.”", "[Oscar Wilde]" },
{ "”Those who dream by day are cognizant of many things which escape those who dream only by night.”", "[Edgar Allan Poe]" },
{ "”You get a little moody sometimes but I think that's because you like to read. People that like to read are always a little fucked up.”", "[Pat Conroy]" },
{ "”The more I know of the world, the more I am convinced that I shall never see a man whom I can really love. I require so much!”", "[Jane Austen]" },
{ "”Tell me, what is it you plan to do with your one wild and precious life?”", "[Mary Oliver]" },
{ "”I like work: it fascinates me. I can sit and look at it for hours.”", "[Jerome K. Jerome]" },
{ "”It is the mark of an educated mind to be able to entertain a thought without accepting it.”", "[Aristotle]" },
{ "”The world is a book and those who do not travel read only one page.”", "[St. Augustine]" },
{ "”Hope is the thing with feathers That perches in the soul And sings the tune without the words And never stops at all.”", "[Emily Dickinson]" },
{ "”If you expect nothing from somebody you are never disappointed.”", "[Sylvia Plath]" },
{ "”The secret of life, though, is to fall seven times and to get up eight times.”", "[Paulo Coelho]" },
{ "”If we knew what it was we were doing, it would not be called research, would it?”", "[Albert Einstein]" },
{ "”Sarcasm is the last refuge of the imaginatively bankrupt.”", "[Cassandra Clare]" },
{ "”And now here is my secret, a very simple secret: It is only with the heart that one can see rightly; what is essential is invisible to the eye.”", "[Antoine de Saint-ExupÃ©ry]" },
{ "”I have no special talents. I am only passionately curious.”", "[Albert Einstein]" },
{ "”Life is a book and there are a thousand pages I have not yet read.”", "[Cassandra Clare]" },
{ "”I am not young enough to know everything.”", "[Oscar Wilde]" },
{ "”One day I will find the right words, and they will be simple.”", "[Jack Kerouac]" },
{ "”If a cluttered desk is a sign of a cluttered mind, of what, then, is an empty desk a sign?”", "[Laurence J. Peter]" },
{ "”I have decided to stick to love...Hate is too great a burden to bear.”", "[Martin Luther King Jr.]" },
{ "”Faithless is he that says farewell when the road darkens.”", "[J.R.R. Tolkien]" },
{ "”What's meant to be will always find a way”", "[Trisha Yearwood]" },
{ "”Always do what you are afraid to do.”", "[Ralph Waldo Emerson]" },
{ "”Give a girl the right shoes, and she can conquer the world.”", "[Bette Midler]" },
{ "”Make it a rule never to give a child a book you would not read yourself.”", "[George Bernard Shaw]" },
{ "”Our lives begin to end the day we become silent about things that matter.”", "[Martin Luther King Jr.]" },
{ "”Of all sad words of tongue or pen, the saddest are these, 'It might have been.”", "[John Greenleaf Whittier]" },
{ "”A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.”", "[George Bernard Shaw]" },
{ "”They say a person needs just three things to be truly happy in this world: someone to love, something to do, and something to hope for.”", "[Tom Bodett]" },
{ "”The boy never cried again, and he never forgot what he'd learned: that to love is to destroy, and that to be loved is to be the one destroyed.”", "[Cassandra Clare]" },
{ "”Pain is inevitable. Suffering is optional.”", "[haruki murakami]" },
{ "”If you're reading this...Congratulations, you're alive.If that's not something to smile about,then I don't know what is.”", "[Chad Sugg]" },
{ "”Faith is taking the first step even when you can't see the whole staircase.”", "[Martin Luther King Jr.]" },
{ "”In the end, we will remember not the words of our enemies, but the silence of our friends.”", "[Martin Luther King Jr.]" },
{ "”Life can only be understood backwards; but it must be lived forwards.”", "[SÃ¸ren Kierkegaard]" },
{ "”The flower that blooms in adversity is the rarest and most beautiful of all.”", "[Walt Disney Company]" },
{ "”Monsters are real, and ghosts are real too. They live inside us, and sometimes, they win.”", "[Stephen King]" },
{ "”And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom.”", "[Anais Nin]" },
{ "”I took a deep breath and listened to the old brag of my heart. I am, I am, I am.”", "[Sylvia Plath]" },
{ "”Any fool can know. The point is to understand.”", "[Albert Einstein]" },
{ "”Talent hits a target no one else can hit. Genius hits a target no one else can see.”", "[Arthur Schopenhauer]" },
{ "”Books so special and rare and yours that advertising your affection feels like a betrayal.”", "[John Green]" },
{ "”You have enemies? Good. That means you've stood up for something, sometime in your life.”", "[Winston Churchill]" },
{ "”We delight in the beauty of the butterfly, but rarely admit the changes it has gone through to achieve that beauty.”", "[Maya Angelou]" },
{ "”Once you learn to read, you will be forever free.”", "[Frederick Douglass]" },
{ "”There are two motives for reading a book; one, that you enjoy it; the other, that you can boast about it.”", "[Bertrand Russell]" },
{ "”I want to stand as close to the edge as I can without going over. Out on the edge you see all kinds of things you can't see from the center.”", "[Kurt Vonnegut]" },
{ "”Hearts are made to be broken.”", "[Oscar Wilde]" },
{ "”Whether you think you can, or you think you can't--you're right.”", "[Henry Ford]" },
{ "”Two people in love, alone, isolated from the world, that's beautiful.”", "[Milan Kundera]" },
{ "”The mind is its own place, and in itself can make a heaven of hell, a hell of heaven..”", "[John Milton]" },
{ "”Accept who you are. Unless you're a serial killer.”", "[Ellen DeGeneres]" },
{ "”Think of all the beauty still left around you and be happy.”", "[Anne Frank]" },
{ "”I did not attend his funeral, but I sent a nice letter saying I approved of it.”", "[Mark Twain]" },
{ "”Where is human nature so weak as in the bookstore?”", "[Henry Ward Beecherr]" },
{ "”In a time of deceit telling the truth is a revolutionary act.”", "[George Orwell]" },
{ "”Somewhere, something incredible is waiting to be known.”", "[Carl Sagan]" },
{ "”Here's all you have to know about men and women: women are crazy, men are stupid. And the main reason women are crazy is that men are stupid.”", "[George Carlin]" },
{ "”\"I am a man\" he told her, \"and men do not consume pink beverages. Get thee gone woman, and bring me something brown.”", "[Cassandra Clare]" },
{ "”A thing is not necessarily true because a man dies for it.”", "[Oscar Wilde]" },
{ "”\"Not everything is about you,\" Clary said furiously.\"Possibly,\" Jace said, \"but you do have to admit that the majority of things are.”", "[Cassandra Clare]" },
{ "”The best index to a person's character is how he treats people who can't do him any good, and how he treats people who can't fight back.”", "[Abigail Van Buren]" },
{ "”I cannot live without books.”", "[Thomas Jefferson]" },
{ "”You don't love someone for their looks, or their clothes, or for their fancy car, but because they sing a song only you can hear.”", "[oscar wilde]" },
{ "”If at first you don't succeed, try, try again. Then quit. No use being a damn fool about it.”", "[W.C. Fields]" },
{ "”Experience is merely the name men gave to their mistakes.”", "[Oscar Wilde]" },
{ "”It is hard enough to remember my opinions, without also remembering my reasons for them!”", "[Friedrich Nietzsche]" },
{ "”Waiting is painful. Forgetting is painful. But not knowing which to do is the worst kind of suffering.”", "[Paulo Coelho]" },
{ "”This above all: to thine own self be true, And it must follow, as the night the day, Thou canst not then be false to any man.”", "[William Shakespeare]" },
{ "”Fantasy is hardly an escape from reality. It's a way of understanding it.”", "[Lloyd Alexander]" },
{ "”God created war so that Americans would learn geography.”", "[Mark Twain]" },
{ "”I can't imagine a man really enjoying a book and reading it only once.”", "[C.S. Lewis]" },
{ "”You know, you could live a thousand lifetimes and not deserve him.”", "[Suzanne Collins]" },
{ "”For the two of us, home isn't a place. It is a person. And we are finally home.”", "[Stephanie Perkins]" },
{ "”What is a friend? A single soul dwelling in two bodies.”", "[Aristotle]" },
{ "”The most courageous act is still to think for yourself. Aloud.”", "[Coco Chanel]" },
{ "”I generally avoid temptation unless I can't resist it.”", "[Mae West]" },
{ "”Not my daughter, you bitch!”", "[J.K. Rowling]" },
{ "”Do not go where the path may lead, go instead where there is no path and leave a trail.”", "[Ralph Waldo Emerson]" },
{ "”I'm not saying that everything is survivable. Just that everything except the last thing is.”", "[John Green]" },
{ "”There is nothing either good or bad, but thinking makes it so.”", "[William Shakespear]" },
{ "”Think before you speak. Read before you think.”", "[Fran Lebowitz]" },
{ "”All happy families are alike; each unhappy family is unhappy in its own way.”", "[Leo Tolstoy]" },
{ "”I have loved the stars too fondly to be fearful of the night.”", "[Sarah   Williams]" },
{ "”All little girls should be told they are pretty, even if they aren't.”", "[Marilyn Monroe]" },
{ "”what matters most is how well you walk through the fire”", "[Charles Bukowski]" },
{ "”It's not true that I had nothing on. I had the radio on.”", "[Marilyn Monroe]" },
{ "”You said you were going for a walk!? What kind of walk takes six hours?""A long one?”", "[Cassandra Clare]" },
{ "”It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.”", "[Jane Austen]" },
{ "”Happiness is a warm puppy.”", "[Charles M. Schulz]" },
{ "”You never have to change anything you got up in the middle of the night to write.”", "[Saul Bellow]" },
{ "”Love is so short, forgetting is so long.”", "[Pablo Neruda]" },
{ "”Courage is the most important of all the virtues because without courage, you can't practice any other virtue consistently.”", "[Maya Angelou]" },
{ "”Either write something worth reading or do something worth writing.”", "[Benjamin Franklin]" },
{ "”The wound is the place where the Light enters you.”", "[Rumi]" },
{ "”Good books don't give up all their secrets at once.”", "[Stephen King]" },
{ "”Don't ever tell anybody anything. If you do, you start missing everybody.”", "[J. D. Salinger]" },
{ "”It is not in the stars to hold our destiny but in ourselves.”", "[William Shakespeare]" },
{ "”He never went out without a book under his arm, and he often came back with two.”", "[Victor Hugo]" },
{ "”Bran thought about it. 'Can a man still be brave if he's afraid?''That is the only time a man can be brave,' his father told him.”", "[George R.R. Martin]" },
{ "”Never let your sense of morals prevent you from doing what is right.”", "[Isaac Asimov]" },
{ "”If you can't fly then run, if you can't run then walk, if you can't walk then crawl, but whatever you do you have to keep moving forward.”", "[Martin Luther King Jr.]" },
{ "”For you, a thousand times over”", "[Khaled Hosseini]" },
{ "”Books may well be the only true magic.”", "[Alice Hoffman]" },
{ "”Hell is empty and all the devils are here.”", "[William Shakespeare]" },
{ "”Everything in the world is about sex except sex. Sex is about power.”", "[Oscar Wilde]" },
{ "”I love to see a young girl go out and grab the world by the lapels. Life's a bitch. You've got to go out and kick ass.”", "[maya angelou]" },
{ "”Try not to become a man of success. Rather become a man of value.”", "[Albert Einstein]" },
{ "”Never allow someone to be your priority while allowing yourself to be their option.”", "[Mark Twain]" },
{ "”I don't know the question, but sex is definitely the answer.”", "[Woody Allen]" },
{ "”No tears in the writer, no tears in the reader. No surprise in the writer, no surprise in the reader.”", "[Robert Frost]" },
{ "”The very essence of romance is uncertainty.”", "[Oscar Wilde]" },
{ "”Turn your wounds into wisdom.”", "[Oprah Winfrey]" },
{ "”Life is a disease: sexually transmitted, and invariably fatal.”", "[Neil Gaiman]" },
{ "”You cannot protect yourself from sadness without protecting yourself from happiness.”", "[Jonathan Safran Foer]" },
{ "”When you have eliminated all which is impossible, then whatever remains, however improbable, must be the truth.”", "[Arthur Conan Doyle]" },
{ "”Many people, myself among them, feel better at the mere sight of a book.”", "[Jane Smiley]" },
{ "”I don't go looking for trouble. Trouble usually finds me.”", "[Katie McGarry]" },
{ "”Man is least himself when he talks in his own person. Give him a mask, and he will tell you the truth.”", "[Oscar Wilde]" },
{ "”Above all, be the heroine of your life, not the victim.”", "[Nora Ephron]" },
{ "”Fantasy is a necessary ingredient in living, it's a way of looking at life through the wrong end of a telescope.”", "[Dr. Seuss]" },
{ "”But luxury has never appealed to me, I like simple things, books, being alone, or with somebody who understands.”", "[Daphne du Maurier]" },
{ "”There is always some madness in love. But there is also always some reason in madness.”", "[Friedrich Nietzsche]" },
{ "”Why fit in when you were born to stand out?”", "[Dr. Seuss]" },
{ "”Men occasionally stumble over the truth, but most of them pick themselves up and hurry off as if nothing had happened.”", "[Winston S. Churchill]" },
{ "”The unexamined life is not worth living.”", "[Socrates]" },
{ "”I wonder how many people I've looked at all my life and never seen.”", "[John Steinbeck]" },
{ "”Everyone should be able to do one card trick, tell two jokes, and recite three poems, in case they are ever trapped in an elevator.”", "[Lemony Snicket]" },
{ "”I have found the paradox, that if you love until it hurts, there can be no more hurt, only more love.”", "[Daphne Rae]" },
{ "”\"You're still trying to protect me. Real or not real,\" he whispers.\"Real,\" I answer. \"Because that's what you and I do, protect each other.”", "[Suzanne Collins]" },
{ "”If you're looking for sympathy you'll find it between shit and syphilis in the dictionary.”", "[David Sedaris]" },
{ "”They love their hair because they're not smart enough to love something more interesting.”", "[John Green]" },
{ "”There are worse crimes than burning books. One of them is not reading them.”", "[Joseph Brodsky]" },
{ "”Kiss me, and you will see how important I am.”", "[Sylvia Plath]" },
{ "”Two possibilities exist: either we are alone in the Universe or we are not. Both are equally terrifying.”", "[Arthur C. Clarke]" },
{ "”Whatever it is you're seeking won't come in the form you're expecting.”", "[Haruki Marukami]" },
{ "”What matters in life is not what happens to you but what you remember and how you remember it.”", "[Gabriel Garcia Marquez]" },
{ "”Wise men speak because they have something to say; fools because they have to say something.”", "[Plato]" },
{ "”Laughter is timeless. Imagination has no age. And dreams are forever.”", "[Walt Disney]" },
{ "”I am very interested and fascinated how everyone loves each other, but no one really likes each other.”", "[Stephen Chbosky]" },
{ "”Beneath the makeup and behind the smile I am just a girl who wishes for the world.”", "[Marilyn Monroe]" },
{ "”As usual, there is a great woman behind every idiot.”", "[John Lennon]" },
{ "”Nobody realizes that some people expend tremendous energy merely to be normal.”", "[Albert Camus]" },
{ "”That's the thing about books. They let you travel without moving your feet.”", "[Jhumpa Lahiri]" },
{ "”Everyone sees what you appear to be, few experience what you really are.”", "[NiccolÃ² Machiavelli]" },
{ "”Being crazy isn't enough.”", "[Dr. Seuss]" },
{ "”Remember: the time you feel lonely is the time you most need to be by yourself. Life's cruelest irony.”", "[Douglas Coupland]" },
{ "”Some tourists think Amsterdam is a city of sin, but in truth it is a city of freedom. And in freedom, most people find sin.”", "[John Green]" },
{ "”Books are mirrors: you only see in them what you already have inside you.”", "[Carlos Ruiz ZafÃ³n]" },
{ "”I have great faith in fools - self-confidence my friends will call it.”", "[Edgar Allan Poe]" },
{ "”Pain and suffering are always inevitable for a large intelligence and a deep heart. The really great men must, I think, have great sadness on earth.”", "[Fyodor Dostoevsky]" },
{ "”Percy wouldn't notice a joke if it danced naked in front of him wearing one of Dobby's hats.”", "[J.K. Rowling]" },
{ "”You must stay drunk on writing so reality cannot destroy you.”", "[Ray Bradbury]" },
{ "”It is said that your life flashes before your eyes just before you die. That is true, it's called Life.”", "[Terry Pratchett]" },
{ "”Man may have discovered fire, but women discovered how to play with it.”", "[Candace Bushnell]" },
{ "”Life is pain, highness. Anyone who says differently is selling something.”", "[William Goldman]" },
{ "”It may be unfair, but what happens in a few days, sometimes even a single day, can change the course of a whole lifetime...”", "[Khaled Hosseini]" },
{ "”Stupid people are dangerous.”", "[Suzanne Collins]" },
{ "”But who prays for Satan? Who, in eighteen centuries, has had the common humanity to pray for the one sinner that needed it most?”", "[Mark Twain]" },
{ "”Time flies like an arrow; fruit flies like a banana.”", "[Anthony G. Oettinger]" },
{ "”If you remember me, then I don't care if everyone else forgets.”", "[Haruki Murakami]" },
{ "”Books are my friends, my companions. They make me laugh and cry and find meaning in life.”", "[Christopher Paolini]" },
{ "”A girl should be two things: classy and fabulous.”", "[Coco Chanel]" },
{ "”I like your Christ, I do not like your Christians. Your Christians are so unlike your Christ.”", "[Mahatma Gandhi]" },
{ "”I have a theory that selflessness and bravery aren't all that different.”", "[Veronica Roth]" },
{ "”Books are like mirrors: if a fool looks in, you cannot expect a genius to look out.”", "[J.K. Rowling]" },
{ "”Stop acting so small. You are the universe in ecstatic motion.”", "[Rumi]" },
{ "”Nothing of me is original. I am the combined effort of everyone I've ever known.”", "[Chuck Palahniuk]" },
{ "”If you are going through hell, keep going.”", "[Winston S. Churchill]" },
{ "”War is peace. Freedom is slavery. Ignorance is strength.”", "[George Orwell]" },
{ "”Education is the most powerful weapon which you can use to change the world.”", "[Nelson Mandela]" },
{ "”My daddy said, that the first time you fall in love, it changes you forever and no matter how hard you try, that feeling just never goes away.”", "[Nicholas Sparks]" },
{ "”I don't mind living in a man's world, as long as I can be a woman in it.”", "[Marilyn Monroe]" },
{ "”The simple things are also the most extraordinary things, and only the wise can see them.”", "[Paulo Coelho]" },
{ "”My ambition is handicapped by laziness”", "[Charles Bukowski]" },
{ "”Painting is poetry that is seen rather than felt, and poetry is painting that is felt rather than seen.”", "[Leonardo da Vinci]" }
};


#endif // QUOTES_H
